version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  web:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5433/${POSTGRES_DB}
      SECRET_KEY: ${SECRET_KEY}
      WEB_PASSWORD: ${WEB_PASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.drlingo-web.rule=Host(`drlingo.alefka.nl`)"
      - "traefik.http.routers.drlingo-web.entrypoints=websecure"
      - "traefik.http.routers.drlingo-web.tls.certresolver=myresolver"
      - "traefik.http.services.drlingo-web.loadbalancer.server.port=80"
volumes:
  dbdata: