version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      SCRIPT_NAME: /pgadmin4
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ede-pgadmin4.rule=Host(`drlingo.alefka.nl`) && PathPrefix(`/pgadmin4/`)"
      - "traefik.http.routers.ede-pgadmin4.entrypoints=websecure"
      - "traefik.http.routers.ede-pgadmin4.tls.certresolver=myresolver"
      - "traefik.http.services.ede-pgadmin4.loadbalancer.server.port=80" 
  web:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      SECRET_KEY: ${SECRET_KEY}
      WEB_PASSWORD: ${WEB_PASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.drlingo-web.rule=Host(`drlingo.alefka.nl`)"
      - "traefik.http.routers.drlingo-web.entrypoints=websecure"
      - "traefik.http.routers.drlingo-web.tls.certresolver=myresolver"
      - "traefik.http.services.drlingo-web.loadbalancer.server.port=5000"
volumes:
  dbdata:
  pgadmin-data:
